cdk added for notification service and chat service
sourcefuse/arc-lambda pull request #31
Opened 2023-07-26 06:16 UTC by Tyagi-Sunny

## Description

cdk added for notification service and chat service

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-13 20:04 UTC, jamescrowley321 approved these changes

2023-08-13 20:04 UTC, jamescrowley321 commented
Let's resolve Sonar issues and get this merged.

2023-08-14 07:58 UTC, Tyagi-Sunny commented
> Let's resolve Sonar issues and get this merged.

@jamescrowley321 code smells and bugs have been removed,
Please review the security hotspots on sonarcloud.

2023-08-18 09:03 UTC, shubhamp-sf requested changes
@Tyagi-Sunny Please reflect the recent Dockerfile and useImage changes in this PR as well before we merge this.

2023-08-18 12:23 UTC, jamescrowley321 approved these changes

2023-08-23 06:34 UTC, merged